config/routes.rb
Rails.application.routes.draw do
  resources :activities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "activities#index"
  get '/activity', to: 'activities#index'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/sessions/new', to: 'sessions#new'
end

app/models/activity.rb
class Activity < ApplicationRecord
  enum activity_type: {
    Ride: 'Ride',
    Run: 'Run',
    Swim: 'Swim',
    Ski: 'Ski'
  }
  validates :name, :activity_type, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json


  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :activity_type, :duration, :distance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to strava_url, allow_other_host: true
  end

  def create
    @response = client.oauth_token(code: params[:code])
  end

  private

  def client
    Strava::OAuth::Client.new(
      client_id: '90376',
      client_secret: '9a31b9066c2942feb97a9a3afb7e7f4d9f1da453'
    )
  end

  def strava_url
    client.authorize_url(
      redirect_uri: 'localhost:3000',
      approval_prompt: 'force',
      response_type: 'code',
      scope: 'profile:read_all,activity:read_all',
    )
  end
  
end

app/controllers/strava_controller.rb
# app/controllers/strava_controller.rb
class StravaController < ApplicationController
  def authorize
    redirect_to Strava::OAuth::AuthorizationRequest.authorization_url(
      client_id: '90376',
      redirect_uri: 'localhost:3000',
      response_type: 'code',
      scope: 'read_all,activity:read_all'
    )
  end

  def callback
    code = params[:code]
    token_response = Strava::OAuth::TokenExchange.exchange(
      client_id: '90376',
      client_secret: '9a31b9066c2942feb97a9a3afb7e7f4d9f1da453',
      code: code
    )

    # Store the access token for the user
    access_token = token_response.access_token

    # Redirect to the page displaying the user's activities
    redirect_to activities_path(access_token: access_token)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Name:</strong>
    <%= activity.name %>
  </p>

  <p>
    <strong>Activity Type:</strong>
    <%= activity.activity_type %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= activity.duration %>
  </p>

  <p>
    <strong>Distance:</strong>
    <%= activity.distance %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :activity_type, style: "display: block" %>
     <%= form.select :activity_type, Activity.activity_types.keys, include_blank: true %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.time_field :duration %>
  </div>

  <div>
    <%= form.label :distance, style: "display: block" %>
    <%= form.text_field :distance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Strava Activities</h1>
<div class="container">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Mileage</th>
      <th>Activity Type</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity[:name] %></td>
        <td><%= activity[:duration] %></td>
        <td><%= activity[:mileage] %></td>
        <td><%= activity[:activity_type] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to "New activity", new_activity_path %>
<%= link_to "Sign in with Strava", "/sessions/new" %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<div class="container">
<%= render "form", activity: @activity %>

<br>

  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strava Alpsman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Strava Alpsman</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><%= link_to "Activities", activities_path %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#"> <%= link_to "New activity", new_activity_path %> </a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


    <%= yield %>
  </body>
</html>